### ISSUE TITLE
GitHub Actions is deprecating 'node12' actions

### ISSUE THREAD

**Issue by simpsont-oci** [ammaraskar/gcc-problem-matcher#4]
Since GitHub Actions is deprecating 'node12' actions, this now pops up warning annotations when it runs in a workflow.

See: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12

**Comment by ammaraskar** [comment]
Thanks again :) new release: https://github.com/ammaraskar/gcc-problem-matcher/releases/tag/0.2.0
