### ISSUE TITLE
GitHub Actions is deprecating 'node16' actions

### ISSUE THREAD

**Issue by glx22** [ammaraskar/gcc-problem-matcher#7]
Since GitHub Actions is deprecating 'node16' actions, this now pops up warning annotations when it runs in a workflow.

See: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by ammaraskar** [comment]
Thanks! Released an update here https://github.com/ammaraskar/gcc-problem-matcher/releases/tag/0.3.0
